services:
  typescript-server:
    container_name: rode-typescript-server
    build:
      context: ./typescript-server
      dockerfile: ./Dockerfile
    environment:
      QUEUE_NAME: "data"
      AMQP_ADDR: "amqp://${USERNAME}:${PASSWORD}@rabbitmq:5672"
    restart: always
    networks:
      - rode
  rust-worker1:
    container_name: rode-rust-worker1
    build:
      context: ./rust-worker
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - rode
    environment:
      QUEUE_NAME: "data"
      ID: "1"
      AMQP_ADDR: "amqp://${USERNAME}:${PASSWORD}@rabbitmq:5672/%2f"
  rust-worker2:
    container_name: rode-rust-worker2
    build:
      context: ./rust-worker
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - rode
    environment:
      QUEUE_NAME: "data"
      ID: "2"
      AMQP_ADDR: "amqp://${USERNAME}:${PASSWORD}@rabbitmq:5672/%2f"
  rabbitmq:
    container_name: rode-rabbitmq
    image: "rabbitmq:4-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - rode
    environment:
      RABBITMQ_DEFAULT_USER: ${USERNAME}
      RABBITMQ_DEFAULT_PASS: ${PASSWORD}

networks:
  rode:
