apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-worker-deployment
  labels:
    app: rust-worker1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rust-worker1
  template:
    metadata:
      labels:
        app: rust-worker1
    spec:
      containers:
      - name: rust-worker1
        image: rode-k8s-test-rust-worker1
        imagePullPolicy: "Never"
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: rabbitmq-config
        - configMapRef:
            name: rust-worker-config

---

apiVersion: v1
kind: Service
metadata:
  name: rust-worker1-service
spec:
  selector:
    app: rust-worker1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
